#!/usr/bin/env python

# @authors: Nick Alekhine, Michael Chadbourne, John Meenagh, Charles Perrone
# @description: Designed to identify files in one directory with matching
#               segments in the other.
# @version: 06-11-2014

# -----------------------------------------------------------------------------
# imports
import sys
import shutil
from parser    import parse
from validator import validate
from adder     import add
from checker   import check
from logger    import log

# -----------------------------------------------------------------------------
# Initialize Operation Struct:
Ocore = OperationsCore(2.5, 75000)


# -----------------------------------------------------------------------------
# Main function, acts based upon OCore['Mode']
output = parse(OCore, sys.argv)
log(output)
output = validate(OCore)
log(output)
output = add(OCore)
log(output)
output = check(OCore)
log(output)

# clean up temporary directory
shutil.rmtree('./tmp/')
